### ISSUE TITLE
Removing any other line than the last one in STR, dosent remove the blank space

### ISSUE THREAD

**Issue by not-lumen** [y3ll0wlife/bug-report-tool#3]
https://i.gyazo.com/8b570e9869803a9cd4786ca6c2be2950.mp4

**Comment by KlukCZ** [comment]
Likely identified the root cause https://cdn.discordapp.com/attachments/605549524420788227/705368753260462171/unknown.png

**Comment by not-lumen** [comment]
Was fixed by removing the STR field and adding a to-do list style instead.
