### ISSUE TITLE
[Light Theme] You can't see text under "select your Action" at CR/CNR and Edit tools

### ISSUE THREAD

**Issue by OndreasCZ** [y3ll0wlife/bug-report-tool#44]
**How to reproduce that:**
1.  Open Bug report tool (if not already)
2. Have light theme
3. Refresh site
4.Observe

**Expected result:** You see text under Select your Action normally

**Actual Result:** You cant see text under "Select your Action"

[YouTube video](https://youtu.be/tkxGgTflkA8)

**Comment by KlukCZ** [comment]
Hey! Could you please provide additional information like your browser and its version? I could not reproduce the issue even after deleting all cookies we use and clearing my cache

**Comment by Miky88** [comment]
CR, Firefox 82.0.3 (64 bit) on Windows 10 Home

**Comment by not-lumen** [comment]
The issue seems to only happen on FireFox

**Comment by Miky88** [comment]
This issue happens only when the page loads, if i switch two times the theme the texts comes back normal

**Comment by OndreasCZ** [comment]
CR on Chrome 86.0.4240.75 (64 bit) on Windows 10 Pro and too on FireFox 82.0.3 (64 bit)

> This issue happens only when the page loads, if i switch two times the theme the texts comes back normal

But as Milky88 mention if you switch themes it goes back to normal.

[YouTube video Chrome](https://youtu.be/qdK9f9UA6dk)

**Comment by KlukCZ** [comment]
The issue should be resolved now. Please let me know if you still can reproduce. I'll keep this issue open until I get confirmation that the issue is fixed

**Comment by OndreasCZ** [comment]
@KlukCZ  I still can reproduce it on  Chrome and on firefox too but on Chrome  I can copy it 


[Chrome copying](https://imgur.com/a/MMU1jyy)

> This issue happens only when the page loads, if i switch two times the theme the texts comes back normal

But it will goes back to normal if you two times switch the themes

**Comment by Miky88** [comment]
Still CR

**Comment by OndreasCZ** [comment]
> The issue should be resolved now. Please let me know if you still can reproduce. I'll keep this issue open until I get confirmation that the issue is fixed

JohnyTheCarrot fixed it only for Edit section but in CR/CNR it still happens

**Comment by Miky88** [comment]
Using the same tricky method as Jhony i added his changes on cr-cnr page too

**Comment by OndreasCZ** [comment]
@Miky88  Oh sorry I was trying to fix that too and I didn't your pull request.

**Comment by KlukCZ** [comment]
Should be resolved now, issue closed. If any further issues arise I'll reopen this if needed

**Comment by Miky88** [comment]
CNR, i can confirm fixes
